#!/bin/bash

VENDOR_DIR=.go
if [[ $GO15VENDOREXPERIMENT == "1" || "$(go version)" =~ "go1.6" ]]; then
  VENDOR_DIR=vendor
fi

declare paths=$(for t in $(find . -name "*_test.go" -not -path "./$VENDOR_DIR/*"); do dirname $t; done | sort | uniq)
declare -i return_value=0

for path in ${paths[@]}; do
  if go test -i $path; then
    echo "$path...ok"
  else
    return_value=1
  fi
done

exit $return_value
