#!/bin/bash

export GOGC=off

declare -i retval=0
for pkg in `go list ./... | fgrep -v 'vendor/'`; do
  go test $pkg
  declare -i code=$?

  if [ $code -eq 0 ]; then
    echo "$pkg...ok"
  else
    echo "$pkg...fail"
  fi

  if [ $retval -eq 0 ]; then
    retval=$code
  fi
done

exit $retval
