#!/bin/bash

export GOGC=off

echo -e "\033[0;36mChecking for compile-time errors\033[0m"
goba || exit 1

echo -e "\033[0;36mRunning tests\033[0m"
go test $(go list ./... | fgrep -v 'vendor/')
result=$?

if hash ponysay 2> /dev/null; then
  if [ $result -eq 0 ]; then
    ponysay "All good!"
  else
    ponysay "Shit's broken"
  fi
fi

exit $result
